name: PR Testing Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.java'
      - '**/pom.xml'
      - 'checkstyle.xml'

jobs:
  TestAPI:
    name: Test API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Run API Tests
        run: |
          mvn test -Denv=dev -Dapi.version=v1

  Linting:
    name: Linting Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Download Checkstyle configuration
        run: |
          curl -o checkstyle.xml https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml

      - name: Run Checkstyle Linting
        run: |
          mvn checkstyle:check -Dcheckstyle.violationSeverity=warning

      - name: Upload Checkstyle Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-report
          path: target/checkstyle-result.xml

    outputs:
      lint_status: ${{ steps.linting.outcome }}

  NotifyFailure:
    name: Notify on Failure
    needs: [TestAPI, Linting]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify Developer
        run: echo "Build failed due to linting or test errors. Please resolve the issues and push again."
